version: 0.0
os: linux
files:
  - source: /ROOT.war
    destination: tmp/codedeploy/
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root